
version: "3"

services:
    web:
        image: nginx:1.14.0-alpine
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
            context: ./phpDockerfile/
        ports: 
            - 9000:9000
        volumes:
            - ./www:/www
    mariadb:
        image: mariadb:10.3
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: passme
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports: 
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: passme